name: Verify CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check gitignore rules
        run: .github/scripts/check-gitignore-rules.sh

      - name: Setup JDK
        id: setup-java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Verify
        run: mvn --batch-mode clean verify

      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: surefire-reports
          path: 'target/surefire-reports/'
